# Generated by Django 6.0.6 on 2026-07-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='endereço')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'unidade de saúde',
                'verbose_name_plural': 'unidades de saúde',
            },
        ),
    ]
