# Generated by Django 6.0.6 on 2026-07-01 01:48

import django.db.models.deletion
import rede_saude.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[rede_saude.validators.validar_cpf], verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='rede_saude.unidadesaude', verbose_name='unidade de saúde')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
            },
        ),
    ]
