# Generated by Django 6.0.6 on 2026-07-01 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
        ('rede_saude', '0002_profissional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, verbose_name='tipo')),
                ('data', models.DateTimeField(verbose_name='data e horário')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('AGUARDANDO_CONFIRMACAO', 'Aguardando confirmação'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('EM_ANALISE', 'Em análise'), ('RESULTADO_DISPONIVEL', 'Resultado disponível'), ('CANCELADO', 'Cancelado')], max_length=23, verbose_name='status')),
                ('resultado', models.TextField(blank=True, default='', verbose_name='resultado')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='exames.agendamento', verbose_name='agendamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='rede_saude.profissional', verbose_name='profissional')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='rede_saude.unidadesaude', verbose_name='unidade de saúde')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'exame',
                'verbose_name_plural': 'exames',
            },
        ),
    ]
