# Generated by Django 6.0.6 on 2026-07-01 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exames', '0002_exame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255, verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('exame', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notificacao_resultado', to='exames.exame', verbose_name='exame')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-pk',),
            },
        ),
    ]
